old_str = input("Enter string with spaces:")
new_str = old_str.replace(" ","")
print("old str is "+old_str)
print("new string after removing spaces "+new_str)
print("length of string after removing spaces is "+str(len(new_str)))